version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app/:/app/
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"

volumes:
  postgres_data: